services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: digestor_user
      POSTGRES_PASSWORD: digestor_pass
      POSTGRES_DB: playground_tables
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  digestor-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - shared_data:/mnt/data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A orgdigestor worker --loglevel=info --concurrency=2
    restart: always
    scale: 4
    volumes:
      - .:/app
      - shared_data:/mnt/data
    depends_on:
      - postgres
      - rabbitmq

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A orgdigestor flower --port=5555
    restart: always

    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq


volumes:
    postgres_data:
    shared_data: