# Generated by Django 5.0.7 on 2024-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgdigestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founded',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='number_of_employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
